#!/bin/sh
if [ "$1" = "conf" ]
then
	make distclean
	./configure sa_lib_dir=. sar_dir=. conf_dir=. conf_file=sysstat.sysconfig sa_dir=tests --enable-debuginfo
elif [ "$1" = "comp" ]
then
	make TFLAGS="-DTEST"
else
	make distclean
	./configure sa_lib_dir=. sar_dir=. conf_dir=. conf_file=sysstat.sysconfig sa_dir=tests --enable-debuginfo && make TFLAGS="-DTEST" && make simtest TFLAGS="-DTEST"
fi
