#!/bin/sh
if [ "$1" = "conf" ]
then
	make distclean
	./configure sa_lib_dir=. sar_dir=. conf_dir=. conf_file=sysstat.sysconfig sa_dir=tests --enable-debuginfo && make CFLAGS="-D TEST"
elif [ "$1" = "comp" ]
then
	make CFLAGS="-D DEBUG -D TEST"
else
	make distclean
	./configure sa_lib_dir=. sar_dir=. conf_dir=. conf_file=sysstat.sysconfig sa_dir=tests --enable-debuginfo && make CFLAGS="-D TEST" && make simtest
fi
